/* app.js : stockage local IndexedDB, connexion Supabase, synchronisation et affichage. Voir GUIDE-TECHNIQUE.md. */
const {url:SUPABASE_URL,publishableKey:SUPABASE_PUBLISHABLE_KEY}=window.SUPABASE_CONFIG;
const configured=SUPABASE_URL.startsWith('https://')&&SUPABASE_PUBLISHABLE_KEY.length>20;
let sbClient=configured?window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY):null;
const $=s=>document.querySelector(s), DB='organiseur-bd', QUEUE='queue';let tasks=[],notes=[],selectedNote=null,user=null,channelA=null,channelB=null,timer=null;
// Horloge locale : elle n'envoie aucune information à Supabase.
function updateClock(){const clock=$('#clock');if(clock)clock.textContent=new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}updateClock();setInterval(updateClock,1000);
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;['tasks','notes',QUEUE].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function db(name,mode,fn){const d=await openDb();return new Promise((ok,no)=>{const t=d.transaction(name,mode),r=fn(t.objectStore(name));t.oncomplete=()=>{d.close();ok(r ? r.result : undefined)};t.onerror=()=>{d.close();no(t.error)}})}const all=n=>db(n,'readonly',s=>s.getAll()),put=(n,x)=>db(n,'readwrite',s=>s.put(x)),drop=(n,id)=>db(n,'readwrite',s=>s.delete(id));
function status(s){const e=$('#sync-status');if(!e)return;let icon='○',label=s,state='idle';if(s.startsWith('Synchronisé')){icon='✓';label='Synchronisation terminée';state='ready'}else if(s.startsWith('Synchronisation')){icon='↻';label='Synchronisation en cours';state='working'}else if(s.startsWith('Hors ligne')){icon='⌁';label='Hors ligne : les changements seront envoyés au retour du réseau';state='offline'}else if(s.startsWith('Erreur')){icon='!';label='Erreur de stockage local';state='error'}else if(s.startsWith('Connexion')){icon='◎';label='Connexion requise';state='idle'}e.textContent=icon;e.title=label;e.setAttribute('aria-label',label);e.dataset.state=state}function loginMessage(s){$('#login-message').textContent=s}function account(x){user=x;$('#login-screen').classList.toggle('hidden',!!user);$('#app-shell').classList.toggle('hidden',!user);$('#signout').classList.toggle('hidden',!user);status(!configured?'Supabase non configuré':user?`Synchronisé : ${user.email}`:'Connexion requise');if(!configured)loginMessage('La configuration Supabase est indisponible.')}
function route(){const v=location.hash==='#notes'?'notes':'todos';document.body.dataset.view=v;$('#todos').classList.toggle('hidden',v!=='todos');$('#notes').classList.toggle('hidden',v!=='notes');document.querySelectorAll('[data-link]').forEach(a=>a.classList.toggle('active',a.dataset.link===v))}addEventListener('hashchange',route);
function renderTasks(){tasks.sort((a,b)=>b.updatedAt-a.updatedAt);const l=$('#task-list');l.replaceChildren();$('#tasks-empty').hidden=tasks.length>0;tasks.forEach(t=>{const li=document.createElement('li');li.className=`task${t.done?' done':''}`;const c=document.createElement('input');c.type='checkbox';c.checked=t.done;c.onchange=async()=>{t.done=c.checked;await change('tasks',t);renderTasks()};const s=document.createElement('span');s.textContent=t.text;const x=document.createElement('button');x.className='delete';x.textContent='×';x.onclick=async()=>{tasks=tasks.filter(q=>q.id!==t.id);await drop('tasks',t.id);await put(QUEUE,{id:`todos:${t.id}`,table:'todos',type:'delete',record:{id:t.id}});renderTasks();sync()};li.append(c,s,x);l.append(li)})}
function renderNotes(){notes.sort((a,b)=>b.updatedAt-a.updatedAt);const l=$('#notes-list');l.replaceChildren();$('#notes-empty').hidden=notes.length>0;notes.forEach(n=>{const card=document.createElement('article');card.className=`note-card${n.id===selectedNote?' selected':''}`;const open=document.createElement('button');open.className='note-open';open.type='button';open.setAttribute('aria-label',`Ouvrir la note ${n.title||'sans titre'}`);const h=document.createElement('strong');h.textContent=n.title||'Sans titre';const p=document.createElement('span');p.textContent=n.content||'Note vide';open.append(h,p);open.onclick=()=>{selectedNote=n.id;renderNotes()};const remove=document.createElement('button');remove.className='delete note-delete';remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',`Supprimer la note ${n.title||'sans titre'}`);remove.onclick=async()=>{notes=notes.filter(x=>x.id!==n.id);selectedNote=selectedNote===n.id?(notes[0]?.id||null):selectedNote;await drop('notes',n.id);await put(QUEUE,{id:`notes:${n.id}`,table:'notes',type:'delete',record:{id:n.id}});renderNotes();sync()};card.append(open,remove);l.append(card)});const n=notes.find(x=>x.id===selectedNote),show=!!n;$('#note-title').classList.toggle('hidden',!show);$('#note-content').classList.toggle('hidden',!show);$('#note-sync').classList.toggle('hidden',!show);$('#delete-note').classList.add('hidden');$('#editor-empty').hidden=show;if(show){$('#note-title').value=n.title;$('#note-content').value=n.content}}
async function change(store,record){record.updatedAt=Date.now();await put(store,record);await put(QUEUE,{id:`${store}:${record.id}`,table:store==='tasks'?'todos':'notes',type:'upsert',record:{...record}});sync()}
async function flush(){if(!user||!navigator.onLine)return;for(const op of await all(QUEUE)){let q;if(op.type==='delete')q=sbClient.from(op.table).delete().eq('id',op.record.id);else{const r=op.record;q=sbClient.from(op.table).upsert({id:r.id,user_id:user.id,text:r.text,title:r.title,content:r.content,done:r.done,created_at:new Date(r.createdAt).toISOString(),updated_at:new Date(r.updatedAt).toISOString()})}const {error}=await q;if(error)throw error;await drop(QUEUE,op.id)}}
async function pull(table){const {data,error}=await sbClient.from(table).select('*').order('updated_at',{ascending:false});if(error)throw error;const mapped=data.map(r=>table==='todos'?({id:r.id,text:r.text,done:r.done,createdAt:Date.parse(r.created_at),updatedAt:Date.parse(r.updated_at)}):({id:r.id,title:r.title,content:r.content,createdAt:Date.parse(r.created_at),updatedAt:Date.parse(r.updated_at)}));if(table==='todos'){tasks=mapped;await Promise.all(tasks.map(x=>put('tasks',x)));renderTasks()}else{notes=mapped;if(!notes.some(x=>x.id===selectedNote))selectedNote=(notes[0] ? notes[0].id : null);await Promise.all(notes.map(x=>put('notes',x)));renderNotes()}}
async function sync(){if(!configured||!user)return;try{status(navigator.onLine?'Synchronisation…':'Hors ligne — sauvegarde locale');await flush();await pull('todos');await pull('notes');account(user);$('#save-state').textContent='Synchronisé'}catch(e){console.error(e);status('Hors ligne — sauvegarde locale')}}
async function subscribe(){if(channelA)await sbClient.removeChannel(channelA);if(channelB)await sbClient.removeChannel(channelB);const o={event:'*',schema:'public',filter:`user_id=eq.${user.id}`};channelA=sbClient.channel(`todos:${user.id}`).on('postgres_changes',{...o,table:'todos'},()=>pull('todos')).subscribe();channelB=sbClient.channel(`notes:${user.id}`).on('postgres_changes',{...o,table:'notes'},()=>pull('notes')).subscribe()}
$('#task-form').onsubmit=async e=>{e.preventDefault();const text=$('#task-input').value.trim();if(!text)return;const now=Date.now(),t={id:crypto.randomUUID(),text,done:false,createdAt:now,updatedAt:now};tasks.unshift(t);await change('tasks',t);$('#task-input').value='';renderTasks()};$('#clear-done').onclick=async()=>{const done=tasks.filter(t=>t.done);tasks=tasks.filter(t=>!t.done);await Promise.all(done.map(async t=>{await drop('tasks',t.id);await put(QUEUE,{id:`todos:${t.id}`,table:'todos',type:'delete',record:{id:t.id}})}));renderTasks();sync()};
$('#new-note').onclick=async()=>{const now=Date.now(),n={id:crypto.randomUUID(),title:'Nouvelle note',content:'',createdAt:now,updatedAt:now};notes.unshift(n);selectedNote=n.id;await change('notes',n);renderNotes();$('#note-title').focus();$('#note-title').select()};function edit(){const n=notes.find(x=>x.id===selectedNote);if(!n)return;n.title=$('#note-title').value.slice(0,160);n.content=$('#note-content').value;clearTimeout(timer);$('#save-state').textContent='Écriture…';timer=setTimeout(async()=>{await change('notes',n);$('#save-state').textContent='Enregistré';renderNotes()},450)}$('#note-title').oninput=edit;$('#note-content').oninput=edit;$('#delete-note').onclick=async()=>{const n=notes.find(x=>x.id===selectedNote);if(!n)return;notes=notes.filter(x=>x.id!==n.id);selectedNote=notes[0] ? notes[0].id : null;await drop('notes',n.id);await put(QUEUE,{id:`notes:${n.id}`,table:'notes',type:'delete',record:{id:n.id}});renderNotes();sync()};
$('#login-form').onsubmit=async e=>{e.preventDefault();const redirectUrl=new URL('.',location.href).href;const {error}=await sbClient.auth.signInWithOtp({email:$('#login-email').value,options:{emailRedirectTo:redirectUrl}});loginMessage(error?error.message:'Lien envoyé : vérifiez vos e-mails puis ouvrez le lien.')};$('#signout').onclick=async()=>{await sbClient.auth.signOut();account(null)};addEventListener('online',sync);
function setTheme(dark){document.body.classList.toggle('dark',dark);localStorage.setItem('organiseur-theme',dark?'dark':'light');document.querySelectorAll('[data-theme-toggle]').forEach(b=>{b.textContent=dark?'☀ Mode clair':'☾ Mode sombre';b.setAttribute('aria-pressed',String(dark))})}const appThemeButton=document.createElement('button');appThemeButton.type='button';appThemeButton.className='theme-toggle';appThemeButton.dataset.themeToggle='';appThemeButton.setAttribute('aria-label','Changer le thème');document.querySelector('#clock').before(appThemeButton);const themeButtons=[appThemeButton,$('#theme-toggle-login')];themeButtons.forEach(b=>{b.dataset.themeToggle='';b.onclick=()=>setTheme(!document.body.classList.contains('dark'))});setTheme(localStorage.getItem('organiseur-theme')==='dark');
(async()=>{[tasks,notes]=await Promise.all([all('tasks'),all('notes')]);renderTasks();renderNotes();route();account(null);if(!configured)return;const {data:{session}}=await sbClient.auth.getSession();account(session?.user||null);if(session?.user){await sync();await subscribe()}sbClient.auth.onAuthStateChange(async(_,s)=>{account(s?.user||null);if(s?.user){await sync();await subscribe()}})})().catch(e=>{console.error(e);status('Erreur de stockage local')});document.querySelector('h1 small').textContent='MD';
