create table if not exists public.todos (id uuid primary key,user_id uuid not null references auth.users(id) on delete cascade,text text not null check(char_length(text) between 1 and 180),done boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.notes (id uuid primary key,user_id uuid not null references auth.users(id) on delete cascade,title text not null default '',content text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.todos enable row level security; alter table public.notes enable row level security;
revoke all on public.todos,public.notes from anon,authenticated; grant select,insert,update,delete on public.todos,public.notes to authenticated;
drop policy if exists "Lire ses tâches" on public.todos; drop policy if exists "Créer ses tâches" on public.todos; drop policy if exists "Modifier ses tâches" on public.todos; drop policy if exists "Supprimer ses tâches" on public.todos;
create policy "Lire ses tâches" on public.todos for select to authenticated using ((select auth.uid())=user_id); create policy "Créer ses tâches" on public.todos for insert to authenticated with check ((select auth.uid())=user_id); create policy "Modifier ses tâches" on public.todos for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "Supprimer ses tâches" on public.todos for delete to authenticated using ((select auth.uid())=user_id);
drop policy if exists "Lire ses notes" on public.notes; drop policy if exists "Créer ses notes" on public.notes; drop policy if exists "Modifier ses notes" on public.notes; drop policy if exists "Supprimer ses notes" on public.notes;
create policy "Lire ses notes" on public.notes for select to authenticated using ((select auth.uid())=user_id); create policy "Créer ses notes" on public.notes for insert to authenticated with check ((select auth.uid())=user_id); create policy "Modifier ses notes" on public.notes for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "Supprimer ses notes" on public.notes for delete to authenticated using ((select auth.uid())=user_id);
do $$ begin alter publication supabase_realtime add table public.todos; exception when duplicate_object then null; end $$; do $$ begin alter publication supabase_realtime add table public.notes; exception when duplicate_object then null; end $$;
